### ISSUE TITLE
onPress events handling

### ISSUE THREAD

**Issue by afilp** [jkomyno/react-native-user-inactivity#1]
Are the ``onPress`` events handled now? Any way to circumvent this? Thanks!

**Comment by jkomyno** [comment]
Hi there, thanks for your interest in this package.
I've just updated react-native's dependency in the Example, and onPress events seem to work perfectly fine at the moment. Tested only on Android, but there's no reason why it shouldn't be fine on iOS too.
Please test it out and reopen thi issue in case :)

**Comment by phungnlg** [comment]
onPress event still haven't been handled, onInactivity still be triggered even after several taps on buttons or screen. 
Please consider this issue. Thanks!

**Comment by mouthzipper** [comment]
got this same issue, have you managed to solve this @phungnlg?

**Comment by ManigandanRaamanathan** [comment]
@jkomyno @mouthzipper @phungnlg @afilp  any updated on this?
