### ISSUE TITLE
Warning - Can't call setState (or forceUpdate) on an unmounted component

### ISSUE THREAD

**Issue by eatoncw** [jkomyno/react-native-user-inactivity#11]
Hi, I'm implementing the UserInactivity component, but getting this warning when I navigate away from the current screen, and unmount that screen.

How do you stop the onAction function once its been rendered? It would be nice to run it at  `componentWillUnmount()`

Thanks!

**Comment by jkomyno** [comment]
Hi, apparently I forgot to clear the timeout when the component gets dismounted, sorry for that.
I should have fixed your issue [here](https://github.com/jkomyno/react-native-user-inactivity/blob/b20a86fdc74feab8c8ecb5bc98cd9507cae83488/src/index.tsx#L51). Please install `react-native-user-inactivity@0.1.3-next`. Closing this for now
