### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by PoppyAnc** [jkomyno/react-native-user-inactivity#12]
Even though on IOS works ok, on android I get "Setting a timer for a long period of time".. warning. 
And even if I make the timeForInactivity to 1 minute (which doesn't produce the error), it never triggers the onAction method with parameter false.

**Comment by andreus3** [comment]
I solved it using react-native-background-timer instead of the regular timer.

**Comment by jkomyno** [comment]
@andreus3 Would it be useful if I provided a function to call to set the timer, that defaults to the current setTimeout?

**Comment by zach-luman** [comment]
No solution for this yet?

**Comment by jkomyno** [comment]
@zach-luman Please look at [the project advancement](https://github.com/jkomyno/react-native-user-inactivity/projects/1), I'm performing a major refactor of the library in order to get a better API and support for custom timers like `react-native-background-timer`.

**Comment by jkomyno** [comment]
Hi, please check out the new version. You need to provide a custom timer to the library. In your case, just use any native background timer that works on Android too.
