### ISSUE TITLE
Doesn't Work On Pause

### ISSUE THREAD

**Issue by JeffreyLeeDave** [jkomyno/react-native-user-inactivity#16]
So I tested this package out on an iOS simulator and console logged for an `timeForInactivity` of 10 sec. It works when the app is in the foreground but does nothing in the background. Is this intentional?

**Comment by jkomyno** [comment]
Hi, this should be fixed using a timer different than the default setTimeout, as I've described in #19.
A new version of this package is expected to be released the 13th August 2019.

**Comment by jkomyno** [comment]
Hi, please check out the new version. You need to provide a custom timer to the library. In your case, just use any native background timer that works on pause too.
