### ISSUE TITLE
Setting timeForInactivity > 60000 causes Android to crash when screen is touched (and triggers timeout period reset)

### ISSUE THREAD

**Issue by NotifydLLC** [jkomyno/react-native-user-inactivity#17]
This doesn't appear to be an issue for iOS which is odd. The error returned is:

"Uncaught Error: t.startWith is not a function."

**Comment by jkomyno** [comment]
Thanks for notifying this, I'm looking forward finding an alternative with a native timeout function, since I suspect there's a problem with how setTimeout() is implemented on Android.
Unfortunately I'm really busy at the moment with my Bachelor's but I aim to fix this before 15 August.

**Comment by jkomyno** [comment]
You need to use a native timer, as specified in the new documentation. v1.0.0 now supports custom timers, so you can provide them to the library.
