### ISSUE TITLE
Timeout not reset when user typing on keyboard

### ISSUE THREAD

**Issue by Bigdragon13th** [jkomyno/react-native-user-inactivity#2]
In my app, there's a textinput inside UserInactivity element. And when user typing in textinput, UserInactivity doesn't reset the timeout and therefore trigger onInactivity even if the app is not technically inactive.

**Comment by Bigdragon13th** [comment]
Also, clicking buttons doesn't reset timeout as well.

**Comment by jkomyno** [comment]
Thanks! It would be great if you could link a Github repository with a minimal reproducible example with the above issue, to speed up testing and bug fixing

**Comment by alan-lam-decathlon** [comment]
+1

**Comment by alan-lam-decathlon** [comment]
I added a call to this.setIsActive() inside the onStartShouldSetPanResponderCapture function, and this seems to work for the button clicks.

**Comment by BlagojeV93** [comment]
Any updates for TextInput typing?

**Comment by jkomyno** [comment]
@Bigdragon13th @alan-lam-decathlon please check the version in the [development branch](https://github.com/jkomyno/react-native-user-inactivity/tree/dev). It's published on npm as `react-native-user-inactivity@0.1.0-next`

**Comment by jkomyno** [comment]
@Bigdragon13th I just had the opportunity to verify that the approach used by this library only works with pure JS Views/Components. Unfortunately, React Native doesn't seem to offer ways of knowing whenever a native component has been touched or not. For instance, native `Alert`s or `TextInput`s aren't catched by PanResponder's methods, and I couldn't find other alternatives. So I guess that cases aren't supported :(

**Comment by ManigandanRaamanathan** [comment]
@jkomyno could you please provide us a reference which we can manually call it whenever the alert or keyboard component is used by us? it will be helpful if you provide code snippet for creating our own reference to it. Thanks
