### ISSUE TITLE
Not working if add alert component to check inactivity at the end of the timer

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [jkomyno/react-native-user-inactivity#23]
@jkomyno  Not working if add alert component to check inactivity at the end of the timer. I'm aware that it works only if the user touch the surface. However, there is events where we have to use the alert component.

Is it possible to provide a reference for us to use it within the alert component to mark it as active? 

or could you provide the codes for initialising the reference to the type script component. Thanks.

**Comment by jkomyno** [comment]
Please try with the new updated version. Reopen the issue in case.
