### ISSUE TITLE
Duplicate Module error

### ISSUE THREAD

**Issue by arabbott** [jkomyno/react-native-user-inactivity#26]
Thank you for this library.  I have been using it in my react-native/expo app for several months.  However, I am in the process of upgrading my app to Expo's SDK v35. I saw the v1.0.0 of this was out (I was on v0.1.3-next); so I upgraded.

When doing so, and trying to start my app `expo start`, I recieve an error:
`Duplicate module name: react-animated` from this library.

Downgrading to `0.1.3-next` sorts the error; however, I always like to keep my dependencies somewhat up-to-date.

Thx in advance

**Comment by jkomyno** [comment]
Please try version 1.0.1 and reopen the issue if the problem isn't gone.
