### ISSUE TITLE
Conflict with React

### ISSUE THREAD

**Issue by salomaoluiz** [jkomyno/react-native-user-inactivity#28]
Hi, I'm re-open the issue #25 because of unfortunately not works, I upgraded to version:
"react-native-user-inactivity": "^1.0.1-beta.1",
and I continue receiving the error, and if I delete ```node_modules``` folder in the lib folder, it works again.

**Comment by jkomyno** [comment]
Sorry for the troubles @salomaoluiz.
Package version 1.0.1 is now online.
Apparently last week my `npm publish` command failed and I didn't notice until today.

(For the record, I was on a train using my mobile phone's hotspot WiFi, so the connection was pretty unstable, lol.)

https://www.npmjs.com/package/react-native-user-inactivity
