### ISSUE TITLE
Haste Module naming collision

### ISSUE THREAD

**Issue by kristinadarroch** [jkomyno/react-native-user-inactivity#29]
jest-haste-map: Haste module naming collision:

**Duplicate module name: react-native**
_paths_: project-name/node_modules/react-native-user-inactivity/node_modules/react-native/package.json collides with project-namel/node_modules/react-native/package.json

**jest-haste-map: Haste module naming collision:
  Duplicate module name: react-animated**

_Paths_: project-name/node_modules/react-native-user-inactivity/node_modules/react-native/Libraries/Animated/release/package.json collides with project-name/node_modules/react-native/Libraries/Animated/release/package.json

**This warning is caused by `hasteImpl` returning the same name for different files.
jest-haste-map: Haste module naming collision:
  Duplicate module name: Sample**

Paths: project-name/node_modules/react-native-user-inactivity/node_modules/react-native/Libraries/Sample/package.json collides with /project-name/FreshTool/node_modules/react-native/Libraries/Sample/package.json

**Comment by kristinadarroch** [comment]
try clearing the Watchman and packager caches with `watchman watch-del-all && react-native start --reset-cache`

**Comment by jkomyno** [comment]
Similar stories in other repositories:
- https://github.com/webpack/webpack/issues/8607#issuecomment-453068938
- https://github.com/facebook/react/issues/14257

**Comment by cmcaboy** [comment]
I am getting the same error on the latest version.

**Comment by cmcaboy** [comment]
I am getting the error on 1.0.1-beta.1, but it looks like you fixed the issue with the [very next commit](https://github.com/jkomyno/react-native-user-inactivity/commit/d945f52a752e02737b002e8e663ebabc1250b69a). Solution was to remove react and react-native from the dependency list.

**Comment by mowbell** [comment]
v1.0.1 is not on npm registry
Last now is: 1.0.1-beta.1

**Comment by cmcaboy** [comment]
I am using a forked version of 1.0.1. I can confirm that it works.

**Comment by jkomyno** [comment]
Sorry for the troubles @mowbell @cmcaboy @kristinadarroch.
Package version 1.0.1 is now online.
Apparently last week my `npm publish` command failed and I didn't notice until today.

(For the record, I was on a train using my mobile phone's hotspot WiFi, so the connection was pretty unstable, lol.)

https://www.npmjs.com/package/react-native-user-inactivity
