### ISSUE TITLE
in iOS plugin is not working

### ISSUE THREAD

**Issue by mylearning76** [jkomyno/react-native-user-inactivity#30]
in iOS plugin is not working.
 "react": "16.8.6",
"react-native": "0.60.4",
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-02-05 at 23 03 29](https://user-images.githubusercontent.com/53185020/73867086-0a9dc100-486c-11ea-8bbf-866d214c44e5.png)

**Comment by jkomyno** [comment]
I'm not able to reproduce. Are you sure this is a problem with the `react-native-user-activity` package? Maybe I'm wrong, but to me this is a `react-native` build error due to some kind of misconfiguration.

**Comment by jkomyno** [comment]
It looks like it's working on [Expo](https://snack.expo.io/J1U1agicK).
Can you maybe try to upgrade your react-native version to at least 0.61? Your target version is 2 major versions behind the most recent, stable react-native version.

**Comment by jkomyno** [comment]
Closed for inactivity.
