### ISSUE TITLE
What number of timer can I set?

### ISSUE THREAD

**Issue by Goldyukol** [jkomyno/react-native-user-inactivity#31]
Do you have any timer limit? Because when I put a lot of importance, warning pops up for me.

`Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. See (https://github.com/facebook/react-native/issues/12981) for more info. (Saw setTimeout with duration 111862ms)`

**Comment by jkomyno** [comment]
As noted in the warning, you should refer to issue [#12981](https://github.com/facebook/react-native/issues/12981) in the react-native repo. This library has nothing to do with that warning.
