### ISSUE TITLE
Usage With React Navigation

### ISSUE THREAD

**Issue by mdaronco** [jkomyno/react-native-user-inactivity#32]
Relevant app dependencies:
```
"react-native": "0.61.5",
"@react-navigation/bottom-tabs": "5.5.0",
"@react-navigation/drawer": "5.8.0",
"@react-navigation/material-bottom-tabs": "5.2.8",
"@react-navigation/native": "5.4.3",
"@react-navigation/stack": "5.4.0",
"react-native-background-timer": "^2.2.0",
"react-native-user-inactivity": "^1.1.0",
```

React Navigation v5 allows routers to be React components. I have a `Main` router that defines routes that are available once a user has logged in. I would like to logout the user if they have met the inactivity threshold on any of these screens. Here is the `Main` router:

```
const MainRouter: FC<MainRouterProps> = ({ deviceInfo }: MainRouterProps) => {
	const isTablet = getDeviceInfoValue(deviceInfo, 'is_tablet');

	return (
		<InactivityMonitor>
			<DrawerStack.Navigator 
				initialRouteName='Dashboard'
				drawerType='front'
				backBehavior='history'
				lazy={true}
				hideStatusBar={false}
				minSwipeDistance={200}
				drawerContent={(props) => <Drawer {...props} />}
			>
				<DrawerStack.Screen 
					name='Dashboard' 
					component={Dashboard} 
				/>
				<DrawerStack.Screen 
					name='Workroom' 
					component={WorkroomRouter} 
				/>
				<DrawerStack.Screen 
					name='Libraries' 
					component={Libraries} 
				/>
				<DrawerStack.Screen 
					name='Directory' 
					component={Directory}
				/>
				<DrawerStack.Screen 
					name='DirectorySearch' 
					component={DirectorySearch} 
				/>
				<DrawerStack.Screen 
					name='SearchResults' 
					component={SearchResults} 
				/>
				<DrawerStack.Screen 
					name='Profile' 
					component={ProfileRouter} 
				/>
				<DrawerStack.Screen 
					name='ProfileSearch' 
					component={ProfileRouter} 
				/>
				<DrawerStack.Screen 
					name='Settings' 
					component={isTablet ? SettingsTablet : SettingsRouter} 
				/>
			</DrawerStack.Navigator>
		</InactivityMonitor>
	);
}
```

the `InactivityMonitor` component wraps the `UserInactivity` component from the `react-native-user-inactivity` package and is implemented as such:

```
import React, { FC, ReactNode, useEffect, useState, memo } from 'react';
import { NativeModules } from 'react-native';
import UserInactivity from 'react-native-user-inactivity';
import BackgroundTimer from 'react-native-user-inactivity/lib/BackgroundTimer';
import { useNavigation } from '@react-navigation/native';
import { IAlertDialogContextItem } from '../../contexts/alertDialog/AlertDialogProvider';
import { compose, withDb, withAlertDialog } from '../../hocs';
import { getPortalAndUserIds } from '../../storage';
import { IDatabase, INativeModules } from '../../types';
import { logError, translate } from '../../util';

interface InactivityMonitorProps {
	children: ReactNode;
	db: IDatabase;
	enqueueAlertDialog: (item: IAlertDialogContextItem | any) => void;
}

const InactivityMonitor: FC<InactivityMonitorProps> = ({ children, db, enqueueAlertDialog }) => {
	const [active, setActive] = useState<boolean>(true);
	const [timer, setTimer] = useState<number>(1000 * 60 * 60 * 3); // default 3 hours
	const navigation = useNavigation();

	useEffect(() => {
		getPortalInactivityTimeout();
	}, []);

	useEffect(() => {
		if (!active) {
			onInactiveTimeout();
		}
	}, [active]);

	const getPortalInactivityTimeout = async () => {
		console.log('InactivityMonitor: mounting. Calling getPortalInactivityTimeout()');

		try {
			const { portalPk } = await getPortalAndUserIds();
			const timeoutMs = await db.read.mobileInactivityTimeout(portalPk);

			console.log('InactivityMonitor: timeoutMs:', timeoutMs);

			if (timeoutMs > 0) {
				setTimer(timeoutMs);
			}
		} catch (error) {
			logError(error, 'InactivityMonitor getPortalInactivityTimeout()');
		}
	};

	const onInactiveTimeout = () => {
		console.log('InactivityMonitor: calling onInactiveTimeout()');

          const { RNViewerMethods } = NativeModules as INativeModules;
		RNViewerMethods.closeViewerScreen();
		navigation.navigate('DeviceAuth');
		enqueueAlertDialog && enqueueAlertDialog({ message: translate('session_timeout') });
	};

	return (
		<UserInactivity
			isActive={active}
			timeForInactivity={timer}
			// @ts-ignore
			timeoutHandler={BackgroundTimer}
			onAction={(isActive) => { setActive(isActive); }}
		>
			{children}
		</UserInactivity>
	);
};

export default compose(
	memo,
	withDb,
	withAlertDialog
)(InactivityMonitor);
```

it looks like any screen interactions (including button presses, etc) do NOT reset the timer given this use case. I have tested with a 1 min (`60000ms`) expiration several times, and the `onAction` function is ran even if I am in the middle of touching the screen or otherwise interacting with the UI. Does the `UserInactivity` component only reset the timer if its immediate children are touched or interacted with on the device's screen?

**Comment by jkomyno** [comment]
@mdaronco I noticed you closed the issue. If you found the solution to your problem, can you please share it with us here? :)

**Comment by mdaronco** [comment]
Hi @jkomyno , first off thanks for the slick module! I'm happy to see you've re-written it using the newer hooks API. 

My problem was that I was setting a drawer navigator as the immediate child node of `UserInactivity`, which caused the `PanResponder` to only reset the timer when interaction with **only** the drawer content occurred. Elevating `InactivityMonitor` up the component tree along with a little ref magic solved that issue for me.

However, I am experiencing weird issues with the timer itself. Initially, I set the timer to a high value (`8640000000` which is 100 days in milliseconds) . Once I know the timeout required for a particular client, call `setTimer` to update the `timeForInactivity` prop passed to `UserInactivity`. Currently, I am testing a client timeout of `60000`, or 1 minute. 

After a few minutes, I'm noticing behavior similar to [#19 ](https://github.com/jkomyno/react-native-user-inactivity/issues/19) `such as the onAction function firing too frequently (faster than the timeForInactivity interval).`

I'm using this timer:
```
import BackgroundTimer from 'react-native-user-inactivity/lib/BackgroundTimer';
```
do you recommend a different native timer or should I implement one myself?

**Comment by jkomyno** [comment]
@mdaronco Thank you for your kind words!

I'm suspecting that [`react-native-background-timer`](https://github.com/ocetnik/react-native-background-timer), which is wrapped by this library's `lib/BackgroundTimer.ts`, might be the cause of that problem. I've also just noticed that the third-party dependency I'm relying on has a surprising amount of [issues](https://github.com/ocetnik/react-native-background-timer/issues), many more than when I wrapped it.

I haven't used React Native in a while and I'm in the middle of University exams right now, but I'll try to look more into it in July/August. Obviously, you're welcome to open a PR yourself! I'd love to see some contribution by others

**Comment by mdaronco** [comment]
Importing the native bg timer directly from `react-native-background-timer` looks to have solved my issue:
```
import BackgroundTimer from 'react-native-background-timer';
```
dependencies are at the time of the comment
```
"react-native-background-timer": "^2.2.0",
"react-native-user-inactivity": "^1.1.0",
```
in case it helps anyone with a similar issue.

Good luck on those exams!

**Comment by iamandiradu** [comment]
This workaround worked for me too. 

> Importing the native bg timer directly from `react-native-background-timer` looks to have solved my issue:
> 
> ```
> import BackgroundTimer from 'react-native-background-timer';
> ```
> 
> dependencies are at the time of the comment
> 
> ```
> "react-native-background-timer": "^2.2.0",
> "react-native-user-inactivity": "^1.1.0",
> ```
> 
> in case it helps anyone with a similar issue.
> 
> Good luck on those exams!

This worked for me.
