### ISSUE TITLE
Error: Attempted to remove more RTCKeyboardObserver Listeners than needed

### ISSUE THREAD

**Issue by Chiinyee** [jkomyno/react-native-user-inactivity#35]
Context: 
React native 0.62.2
iOS 13

How i implemented:

const logout = () => {
       props.navigation.navigate('Splash')
 }

   <UserInactivity
      isActive={active}
      timeForInactivity={timer}
      onAction={isActive => { isActive ? console.log("I'm active") : logout() }}>

 // App components

 </UserInactivity>

I am attempting to use this library to detect for user inactivity and if the user is inactive, I would like to log the user out of the app. When the logout() method is called and the page is routed to splash, I get the following error: Attempted to remove more RTCKeyboardObserver Listeners than needed. May I know if this is a problem due to the library?

![Screenshot 2020-06-12 at 3 06 36 PM](https://user-images.githubusercontent.com/43974785/84475406-176d6e00-acbf-11ea-9e38-4f38cd92bcdd.png)

**Comment by betancourtYeison** [comment]
You can use `skipKeyboard={true}` to fixed while the issue is fixed

**Comment by jkomyno** [comment]
Hi @Chiinyee, can you please provide a minimal example Expo application with the issue you're describing?

**Comment by wilq32-pwitkowski** [comment]
I got same problem in my application, and I can confirm that adding skipKeyboard={true} solves the problem.

**Comment by jkomyno** [comment]
Hi to all, `react-native-user-inactivity@1.2.0` is out with this update.
