### ISSUE TITLE
onAction getting called twice

### ISSUE THREAD

**Issue by robbienohra** [jkomyno/react-native-user-inactivity#36]
Recreate:

```js
<View>
      <UserInactivity
        isActive={active}
        timeForInactivity={5000}
        timeoutHandler={BackgroundTimer}
        onAction={(isActive) => {
          console.log(isActive);
        }}
        style={{flex: 1, paddingTop: '10%'}}>
        <Text>Foo</Text>
      </UserInactivity>
    </View>
```

Behavior: 

`console.log` gets called _twice_ every 5 seconds

I'm using this background timer:

`
import BackgroundTimer from 'react-native-user-inactivity/lib/BackgroundTimer';
`

Expected behavior:

`onAction` should only be called _once_

**Comment by robbienohra** [comment]
The problem actually seems to get even worse the more times you click before the active status switches back to active

**Comment by robbienohra** [comment]
Like every time you click the screen the number of console logs multiplies in the inactive case.

**Comment by robbienohra** [comment]
I determined it seems like `cancelTimer` is getting called twice
investigating further now

**Comment by robbienohra** [comment]
It seems to be this line that triggers the second cancel: 

https://github.com/jkomyno/react-native-user-inactivity/blob/master/src/index.tsx#L168

The call to:

`setDate(Date.now())`

I'll see if I can somehow differentiate between when this get triggered in the case where the user has touched the screen vs. when the inactivity time has elapsed.

**Comment by robbienohra** [comment]
Yeah looks like there's some contention between the `useEffect` that triggers `resetTimerDueToActivity` dependency on `active`:

https://github.com/jkomyno/react-native-user-inactivity/blob/master/src/index.tsx#L104

and the `useTimeout` dependency on `date`:

https://github.com/jkomyno/react-native-user-inactivity/blob/master/src/index.tsx#L119

that's creating an infinite loop type of situation

**Comment by robbienohra** [comment]
It actually looks like there's a leak when the timer resets after the defined period of inactivity

**Comment by jkomyno** [comment]
Hi @robbienohra, thank you for opening this issue. How would you propose to solve this issue?

**Comment by robbienohra** [comment]
@jkomyno I got stuck honestly after a few hours I'm not sure if it's related to the `usetimeout-react-hook` maybe not being wired up correctly for the inactivity case vs. the activity case.

There don't appear to be any leaks when the cancellation happens as a function of the user clicking the screen, only when the inactivity window has been reached.

**Comment by robbienohra** [comment]
Based on my tests it seems like multiple instances of `cancelTimer` are being made in the inactivity case.

**Comment by robbienohra** [comment]
I added logs to the timeout hook and I noticed basically that the cancellation is getting called correctly in the case that a user keeps clicking the screen, preventing a leak there. But once the timeout is reset because the inactivity window has been reached in that case it doesn't seem like cancelling an existing `cancelTimer` is working in that case, something like that.

**Comment by robbienohra** [comment]
Sorry wasn't able to reach a solution yet honestly I ran out of time. If you have time to look at it would be great if there's an obvious fix, otherwise I should be able to tackle it again in a few days.

**Comment by layeng** [comment]
Hi I also have problems with the background timer. If I remove the background timer, the inactivity will work in foreground and attract a lot of warnings. But it works.  With background timer, there is no warnings but the application that follows on expiry of inactive timer gets called so many times. That application is logout().  When I subsequently opened the app a long time later, it can't enter the application because it gets logout . In other words, there is no way to cancel the inactivity timer and restart it when the application is reentered. I would be most happy if you have solved the problem and let me know the solution. Thank you.

**Comment by robbienohra** [comment]
@layeng to be honest I abandoned the library altogether
it was too frustrating trying to resolve the issue
there's a fundamental issue with the integration between the native BackgroundTimer library and the usetimeout-react-hook that I wasn't able to resolve sorry

**Comment by robbienohra** [comment]
@layeng @jkomyno for what it's worth I found an elegant Android-specific solution that resolved the performance issue I was having


```
  useEffect(() => {
    const intervalId = BackgroundTimer.setInterval(() => {
      wipeNavigationStack();
      userDispatch({ type: 'AUTOLOGOUT' });
    }, parseInt(signoutTime, 10) * 60000);

    return () => {
      BackgroundTimer.clearInterval(intervalId);
    };
  }, [userDispatch, signoutTime, active]);

  function reset() {
    setActive((a) => !a);
    return false;
  }

  const debounced = debounce(reset, 1000);

  const [panResponder] = useState(
    PanResponder.create({
      onMoveShouldSetPanResponderCapture: debounced,
      onPanResponderTerminationRequest: debounced,
      onStartShouldSetPanResponderCapture: debounced,
    })
  );

  return (
    <View style={{ flex: 1 }} {...panResponder.panHandlers}>
      {children}
    </View>
  );
}
```

basically debounce the reset callback and the gesture events all bubble up into a single event that way

use effect lifecycle handles the reset and bam 

works likes a charm

not sure how I'd back this into the library

but I think the debounce approach at the reset callback level is the way to go

**Comment by layeng** [comment]
Hi Robbie
I don't understand your code. I am not such a great react-native developer.
I am still using the foreground timer. I wish to use background timer but
using BackgroundTimer via timeoutHandler gives me even more bugs in terms
of so many repeated calls. I use the timer inactivity to send a logout api.
Using foreground timer will cause no logout to be sent when the screen goes
into standby. If you know of a better solution, please let me know. Thank
you
