### ISSUE TITLE
react-native-user-inactivity not working in Android 10

### ISSUE THREAD

**Issue by sivaperumaljeyaraj** [jkomyno/react-native-user-inactivity#41]
Hi, I have used this plugin for session timeout in my project and the inactivity time is 20 minutes.

It works in iOS and Android 8. But it is not working in Android 10.

Please help me with this.

**Comment by jkomyno** [comment]
Hi, which timer are you using? Also, have you taken a look at this [page](https://developer.android.com/training/scheduling/wakelock#cpu)?

**Comment by jkomyno** [comment]
This issue might also be connected to this other one: https://github.com/ocetnik/react-native-background-timer/issues/281

**Comment by jkomyno** [comment]
Closed for inactivity.

**Comment by iamandiradu** [comment]
@jkomyno, nice pun. 😂

**Comment by sujayjaju** [comment]
This seems to make it work for me:
```js
import BackgroundTimer from 'react-native-background-timer';

class CustomBackgroundTimer {
  static backgroundTimer = null;
  static clearTimeout = () => {
    if (this.backgroundTimer) {
      BackgroundTimer.clearTimeout(this.backgroundTimer);
    }
    BackgroundTimer.stop();
  };
  static setTimeout = (fn, timeout) => {
    BackgroundTimer.start();
    this.backgroundTimer = BackgroundTimer.setTimeout(fn, timeout);
  };
}
export default CustomBackgroundTimer;
```

**Comment by therealemjy** [comment]
@sujayjaju This solved the issue for me. Thanks!
