### ISSUE TITLE
Keeps timing users out while using the app

### ISSUE THREAD

**Issue by coderwithattitude** [jkomyno/react-native-user-inactivity#44]
Hi @jkomyno, 

Thanks for this awesome contribution to the react native community. I seem to be having some issues with our implementation as users keep getting timed out while they are using our app, and they have to sign back in after which they are immediately timed out. Below is a sample
Of our code 

`
        <UserInactivity
        timeForInactivity={SIGNOUT_INTERVAL}
        timeoutHandler={BackgroundTimer}
        isActive={store.getState().inactivityState}
       onAction={isActive => this.onAction(isActive)}
        >
        <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}>
            <ErrorBoundary>
              <AppContainer
                ref={this.navigation}
                uriPrefix={FLEXCONFIG.deepLinkPrefix}
              />
            </ErrorBoundary>
          </PersistGate>
        </Provider>
        </UserInactivity>'

Thanks for your help in advance.

**Comment by jkomyno** [comment]
Hi @coderwithattitude, thank you for your message. Can you please provide an executable demo for me to understand where the problem might lie? Thank you in advance.

**Comment by jkomyno** [comment]
Closed for inactivity.
