### ISSUE TITLE
Keyboard activity outside this App

### ISSUE THREAD

**Issue by veeramarni** [jkomyno/react-native-user-inactivity#48]
Does the inactivity track within the App or even outside this App. We want to capture any Keyboard events not just within this App to determine the activity of the User. If the app runs in the background and the User use Keyboard in another App, this should consider as Activity. 

In a sense, we want to gather user activity overall with his phone. Will this package works for our case?

**Comment by jkomyno** [comment]
Hi @veeramarni, no, this library doesn't solve your case as it is.
One way of doing that would be to have a background service in your application and adding the following two listeners:

```typescript
import { Keyboard } from 'react-native';

// ...

Keyboard.addListener('keyboardDidHide', () => { /* ... */ });
Keyboard.addListener('keyboardDidShow', () => { /* ... */ });
```

Maybe you can try to take a look at [react-native-background-actions](https://github.com/Rapsssito/react-native-background-actions) by @Rapsssito.

If you ever solve your use case, I gently ask you to report back here with your solution, as it could be useful to other developers in the future.
